### ISSUE TITLE
Integration with Mattermost

### ISSUE THREAD

**Issue by ihr** [kolide/kolide#10]
Hi guys,

Kolide is a very useful project and I thank you for your effort! 

I would like to suggest integration [with http://www.mattermost.org/](http://www.mattermost.org/), since I saw Slack on the README. Mattermost is Slack's open-source equivalent.

**Comment by zwass** [comment]
@ihr Thanks for letting us know about this. We will look into integrating with Mattermost when we get to our integrations.

**Comment by zwass** [comment]
Do we need a mechanism for expiring sessions (besides timeout which is implemented here)?

**Comment by marpaia** [comment]
As part of our [recent announcement](https://github.com/kolide/kolide/commit/85265ca07565640755c3aafd4de64a0414a04b2e), we're going to be taking this into account while working on future features and we'll update the repo with a big update in a few months. I'm going to close this for now, but we're definitely interested in this!
