### ISSUE TITLE
No Nodes Found

### ISSUE THREAD

**Issue by hfakar** [kolide/kolide#15]
I dont know where did i do a mistake but it seems i have no nodes not even localhost. 
And my queries returns "No results found."

Can you help me about that?

**Comment by zwass** [comment]
Hi @hfakar, it looks like you don't have an enrolled `osqueryd` client. Have you started an `osqueryd` client [as specified in the README](https://github.com/kolide/kolide#osqueryd)?

**Comment by hfakar** [comment]
Hi there @zwass 
Yes i did but it gives error. 
 Cannot activate tls logger plugin: No node key, TLS logging disabled. 
Which key is this? Is it `this:`
key = "change-this-ahAJDKFH876A*DS&R*SADf187@#$#%^$%^11+0"
Or anything else?

**Comment by zwass** [comment]
The key you mention there is the "enrollment key" that is used to "enroll" and get a node key. When `osqueryd` starts up it should attempt to contact the Kolide server, which will assign it a node key if osqueryd provides the correct enrollment key.

Please post the full log from running `osqueryd` so that we can try to debug what happened.

**Comment by burdzz** [comment]
@zwass I believe the key he is mentioning is actually the redis session key. 
@hfakar `enroll_secret = ""` is actually where to set the enrollment key.

**Comment by zwass** [comment]
Ah @burdzz you are correct about that being the session key.

@hfakar That key should be fine as long as you are just testing things out.

**Comment by hfakar** [comment]
`I0802 10:45:03.551189  9494 init.cpp:318] osquery initialized [version=1.7.7-13-ge6fbde8]
I0802 10:45:03.559661  9494 system.cpp:193] Found stale process for osqueryd (7998) removing pidfile
I0802 10:45:03.559739  9494 system.cpp:228] Writing osqueryd pid (9494) to /tmp/osquery.pid
I0802 10:45:03.559808  9494 extensions.cpp:209] Could not autoload extensions: Failed reading: /etc/osquery/extensions.load
I0802 10:45:03.560326  9495 watcher.cpp:373] osqueryd watcher (9494) executing worker (9496)
I0802 10:45:03.577057  9496 init.cpp:315] osquery worker initialized [watcher=9494]
I0802 10:45:03.577250  9496 extensions.cpp:216] Could not autoload modules: Failed reading: /etc/osquery/modules.load
I0802 10:45:03.577307  9496 rocksdb.cpp:191] Opening RocksDB handle: /tmp/osquery.db
I0802 10:45:03.741271  9496 tls.cpp:67] TLSEnrollPlugin requesting a node enroll key from: https://localhost:8000/api/v1/osquery/enroll
I0802 10:45:03.741276  9503 interface.cpp:257] Extension manager service starting: /var/osquery/osquery.em
I0802 10:45:03.741578  9496 tls.cpp:216] TLS/HTTPS POST request to URI: https://localhost:8000/api/v1/osquery/enroll
{"enroll_secret":"","host_identifier":"6f545b39-e275-45cb-9704-52aabbd3b9c6"}

W0802 10:45:03.743027  9496 tls.cpp:74] Failed enrollment request to https://localhost:8000/api/v1/osquery/enroll (Request error: certificate verify failed) retrying...
I0802 10:45:03.744143  9496 tls.cpp:216] TLS/HTTPS POST request to URI: https://localhost:8000/api/v1/osquery/enroll
{"enroll_secret":"","host_identifier":"6f545b39-e275-45cb-9704-52aabbd3b9c6"}

W0802 10:45:03.744736  9496 tls.cpp:74] Failed enrollment request to https://localhost:8000/api/v1/osquery/enroll (Request error: certificate verify failed) retrying...
I0802 10:45:03.748834  9496 tls.cpp:216] TLS/HTTPS POST request to URI: https://localhost:8000/api/v1/osquery/enroll
{"enroll_secret":"","host_identifier":"6f545b39-e275-45cb-9704-52aabbd3b9c6"}

I0802 10:45:03.749537  9496 tls.cpp:67] TLSEnrollPlugin requesting a node enroll key from: https://localhost:8000/api/v1/osquery/enroll
I0802 10:45:03.749579  9496 tls.cpp:216] TLS/HTTPS POST request to URI: https://localhost:8000/api/v1/osquery/enroll
{"enroll_secret":"","host_identifier":"6f545b39-e275-45cb-9704-52aabbd3b9c6"}

W0802 10:45:03.750193  9496 tls.cpp:74] Failed enrollment request to https://localhost:8000/api/v1/osquery/enroll (Request error: certificate verify failed) retrying...
I0802 10:45:03.751309  9496 tls.cpp:216] TLS/HTTPS POST request to URI: https://localhost:8000/api/v1/osquery/enroll
{"enroll_secret":"","host_identifier":"6f545b39-e275-45cb-9704-52aabbd3b9c6"}

W0802 10:45:03.751899  9496 tls.cpp:74] Failed enrollment request to https://localhost:8000/api/v1/osquery/enroll (Request error: certificate verify failed) retrying...
I0802 10:45:03.756041  9496 tls.cpp:216] TLS/HTTPS POST request to URI: https://localhost:8000/api/v1/osquery/enroll
{"enroll_secret":"","host_identifier":"6f545b39-e275-45cb-9704-52aabbd3b9c6"}

I0802 10:45:03.756795  9496 tls.cpp:216] TLS/HTTPS POST request to URI: https://localhost:8000/api/v1/osquery/config
{"node_key":""}

I0802 10:45:03.758486  9496 tls.cpp:67] TLSEnrollPlugin requesting a node enroll key from: https://localhost:8000/api/v1/osquery/enroll
I0802 10:45:03.758554  9496 tls.cpp:216] TLS/HTTPS POST request to URI: https://localhost:8000/api/v1/osquery/enroll
{"enroll_secret":"","host_identifier":"6f545b39-e275-45cb-9704-52aabbd3b9c6"}

W0802 10:45:03.761258  9496 tls.cpp:74] Failed enrollment request to https://localhost:8000/api/v1/osquery/enroll (Request error: certificate verify failed) retrying...
I0802 10:45:03.766306  9496 tls.cpp:216] TLS/HTTPS POST request to URI: https://localhost:8000/api/v1/osquery/enroll
{"enroll_secret":"","host_identifier":"6f545b39-e275-45cb-9704-52aabbd3b9c6"}

W0802 10:45:03.767041  9496 tls.cpp:74] Failed enrollment request to https://localhost:8000/api/v1/osquery/enroll (Request error: certificate verify failed) retrying...
I0802 10:45:03.771214  9496 tls.cpp:216] TLS/HTTPS POST request to URI: https://localhost:8000/api/v1/osquery/enroll
{"enroll_secret":"","host_identifier":"6f545b39-e275-45cb-9704-52aabbd3b9c6"}

I0802 10:45:03.772102  9496 tls.cpp:216] TLS/HTTPS POST request to URI: https://localhost:8000/api/v1/osquery/config
{"node_key":""}

I0802 10:45:03.776883  9496 tls.cpp:67] TLSEnrollPlugin requesting a node enroll key from: https://localhost:8000/api/v1/osquery/enroll
I0802 10:45:03.776971  9496 tls.cpp:216] TLS/HTTPS POST request to URI: https://localhost:8000/api/v1/osquery/enroll
{"enroll_secret":"","host_identifier":"6f545b39-e275-45cb-9704-52aabbd3b9c6"}

W0802 10:45:03.777968  9496 tls.cpp:74] Failed enrollment request to https://localhost:8000/api/v1/osquery/enroll (Request error: certificate verify failed) retrying...
I0802 10:45:03.779112  9496 tls.cpp:216] TLS/HTTPS POST request to URI: https://localhost:8000/api/v1/osquery/enroll
{"enroll_secret":"","host_identifier":"6f545b39-e275-45cb-9704-52aabbd3b9c6"}

W0802 10:45:03.779927  9496 tls.cpp:74] Failed enrollment request to https://localhost:8000/api/v1/osquery/enroll (Request error: certificate verify failed) retrying...
I0802 10:45:03.784114  9496 tls.cpp:216] TLS/HTTPS POST request to URI: https://localhost:8000/api/v1/osquery/enroll
{"enroll_secret":"","host_identifier":"6f545b39-e275-45cb-9704-52aabbd3b9c6"}

I0802 10:45:03.785086  9496 tls.cpp:216] TLS/HTTPS POST request to URI: https://localhost:8000/api/v1/osquery/config
{"node_key":""}

W0802 10:45:03.786268  9496 init.cpp:554] Error reading config: Request error: certificate verify failed
I0802 10:45:03.786332  9496 tls.cpp:67] TLSEnrollPlugin requesting a node enroll key from: https://localhost:8000/api/v1/osquery/enroll
I0802 10:45:03.786432  9496 tls.cpp:216] TLS/HTTPS POST request to URI: https://localhost:8000/api/v1/osquery/enroll
{"enroll_secret":"","host_identifier":"6f545b39-e275-45cb-9704-52aabbd3b9c6"}

W0802 10:45:03.787243  9496 tls.cpp:74] Failed enrollment request to https://localhost:8000/api/v1/osquery/enroll (Request error: certificate verify failed) retrying...
I0802 10:45:03.788380  9496 tls.cpp:216] TLS/HTTPS POST request to URI: https://localhost:8000/api/v1/osquery/enroll
{"enroll_secret":"","host_identifier":"6f545b39-e275-45cb-9704-52aabbd3b9c6"}

W0802 10:45:03.789082  9496 tls.cpp:74] Failed enrollment request to https://localhost:8000/api/v1/osquery/enroll (Request error: certificate verify failed) retrying...
I0802 10:45:03.793238  9496 tls.cpp:216] TLS/HTTPS POST request to URI: https://localhost:8000/api/v1/osquery/enroll
{"enroll_secret":"","host_identifier":"6f545b39-e275-45cb-9704-52aabbd3b9c6"}

E0802 10:45:03.794257  9496 init.cpp:490] Cannot activate tls logger plugin: No node key, TLS logging disabled.
`

This is what i am facing now. @zwass @burdzz

**Comment by hfakar** [comment]
Hi there @zwass 
Yes i did but it gives error. 
 Cannot activate tls logger plugin: No node key, TLS logging disabled. 
Which key is this? Is it this:
key = "change-this-ahAJDKFH876A*DS&R*SADf187@#$#%^$%^11+0"
Or anything else?

**Comment by zwass** [comment]
Ah, your error now is `Request error: certificate verify failed`. This is because the SSL cert you are using for the Kolide server is being rejected by the HTTPS client in `osqueryd`.

Try running `make certs`, and make sure you use `localhost` when it asks for `Common Name (e.g. server FQDN or YOUR name)`. Then make sure that `kolide` runs with that newly generated certificate set in the config, and `osqueryd` runs with that certificate set by `--tls_server_certs`.

Hopefully that will get you going, but if not, join the [osquery Slack channel](https://osquery-slack.herokuapp.com/) and we can chat in #kolide.
