### ISSUE TITLE
Feature request - LDAP support

### ISSUE THREAD

**Issue by frite** [kolide/kolide#4]
LDAP (maybe AD) support is probably a must. 
It will solve a lot of issues and make the management of it in bigger environments way better.
Ideally, it will also allow users to query hosts that they are allowed to.

**Comment by marpaia** [comment]
Thanks for this! We're actively working on a new iteration of Kolide and we're definitely taking this into account :). I'm going to close this for now, but stay tuned!

**Comment by marpaia** [comment]
Closing this master task as this development will be planned differently with Gnar.
